// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCm5Uu-YV67i6ijzI3OdoKjwDduZZjOwns',
    appId: '1:407694320179:web:544c6d6180f43cfe9ab946',
    messagingSenderId: '407694320179',
    projectId: 'haverr-93683',
    authDomain: 'haverr-93683.firebaseapp.com',
    storageBucket: 'haverr-93683.appspot.com',
    measurementId: 'G-9JJ068931S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwvjGSyR6YSnC8kGle1rY3ckSdWo-1rlg',
    appId: '1:407694320179:android:f2deb5e5a37b50229ab946',
    messagingSenderId: '407694320179',
    projectId: 'haverr-93683',
    storageBucket: 'haverr-93683.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkcJoO0Cc2MmjD2lBXMTxyIENIiTW9uh4',
    appId: '1:407694320179:ios:9a169f3cc306f6a99ab946',
    messagingSenderId: '407694320179',
    projectId: 'haverr-93683',
    storageBucket: 'haverr-93683.appspot.com',
    iosClientId: '407694320179-ut8savdkfvudravkql2avevs69ddct65.apps.googleusercontent.com',
    iosBundleId: 'com.example.haverr',
  );
}
